### ISSUE TITLE
Support the Material theme

### ISSUE THREAD

**Issue by immanuelfodor** [meerkatzenwildschein/shaarli-image-upload#3]
This is an extremely useful plugin that I've just seen in the Shaarli v0.14.0 release notes :partying_face: 

I tried it together with the [Material theme](https://github.com/kalvn/Shaarli-Material) and the additional form field is rendered badly on the new link form.

![image](https://github.com/user-attachments/assets/d7d09b85-39ff-42ed-9dc4-d95346edbd9c)

Could you please provide a fix for it to support the Material theme with a nicely rendered form? 

Note: I had a [similar issue](https://github.com/waschinski/shaarli-targetblank/issues/1) with another plugin and the plugin author could fix it without modifying the theme. However, I mentioned this issue on the Material theme repo, too ([see here](https://github.com/kalvn/Shaarli-Material/issues/136)), I don't know who should fix it, the theme or the plugin author. But maybe you see it first and can do something about it without theme changes.

**Comment by meerkatzenwildschein** [comment]
I'm glad you like the plugin. Since I am not familiar with the Material plugin, I used the HTML-Code from Shaarli under Settings -> Import, where there is also an upload button. This also does not look Material styled, but I have taken over the HTML from there, which already brings an improvement. Everything else will probably have to be implemented by the Material theme so that everything is uniform. I hope I have been able to help you at least a little. Best regards

**Comment by immanuelfodor** [comment]
Thank you for the quick reply! So it seems the theme needs to be adjusted then :/

**Comment by meerkatzenwildschein** [comment]
I think so. I'm curious to see if there will be an answer from the issue of the Material Theme project. Unfortunately, I'm not very familiar with UI things. If there are any suggestions, I will of course make further adjustments.

**Comment by immanuelfodor** [comment]
Well, I applied a quick fix using my [custom CSS plugin](https://github.com/immanuelfodor/shaarli-custom-css). I think it's acceptable until a proper fix from the theme author.
If anybody stumbles upon this issue, this is the config I used with the following result:

`#editlinkform .form-entry script + br { display:none; } #editlinkform .shaarli-image-upload { float:right; }`

![image](https://github.com/user-attachments/assets/e0c4a7e7-15ac-4ffa-ba0a-c087ecc7194d)

![image](https://github.com/user-attachments/assets/d3c9ec62-25c9-4bab-8e77-c7fa946443af)
